import { ProjectType, NewProjectData, CustomInputsState } from './ProjectTypes';

// Sample projects data
export const SAMPLE_PROJECTS: ProjectType[] = [
  {
    id: 1,
    title: 'Real Good Foods 27 May',
    description: 'Price optimization and market research for food products',
    createdDate: '05/27/2025 15:32',
    updatedDate: '05/27/2025 15:32',
    version: '1',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '1',
    updatedAt: new Date('2025-05-27T15:32:00'),
    date_created: new Date('2025-05-27T15:32:00'),
    Models: null,
    project_name: 'Real Good Foods 27 May',
    product_name: 'Food Products'
  },
  {
    id: 2,
    title: 'FreshMart Q2 Analysis',
    description: 'Quarterly pricing strategy for fresh products and price optimization',
    createdDate: '06/15/2025 09:45',
    updatedDate: '07/02/2025 14:20',
    version: '3',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 92,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '3',
    updatedAt: new Date('2025-07-02T14:20:00'),
    date_created: new Date('2025-06-15T09:45:00'),
    Models: null,
    project_name: 'FreshMart Q2 Analysis',
    product_name: 'Fresh Products'
  },
  {
    id: 3,
    title: 'Global Foods Corp',
    description: 'International pricing analysis and recommendations',
    createdDate: '05/10/2025 11:30',
    updatedDate: '06/28/2025 16:15',
    version: '2',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 78,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '2',
    updatedAt: new Date('2025-06-28T16:15:00'),
    date_created: new Date('2025-05-10T11:30:00'),
    Models: null,
    project_name: 'Global Foods Corp',
    product_name: 'International Foods'
  },
  {
    id: 4,
    title: 'SuperValue Market',
    description: 'Value chain optimization for retail products and price optimization',
    createdDate: '07/01/2025 08:20',
    updatedDate: '07/05/2025 17:45',
    version: '1',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 65,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '1',
    updatedAt: new Date('2025-07-05T17:45:00'),
    date_created: new Date('2025-07-01T08:20:00'),
    Models: null,
    project_name: 'SuperValue Market',
    product_name: 'Retail Products'
  },
  {
    id: 5,
    title: 'Organica Foods',
    description: 'Premium organic product pricing strategy',
    createdDate: '06/12/2025 13:10',
    updatedDate: '07/06/2025 10:30',
    version: '2',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 88,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '2',
    updatedAt: new Date('2025-07-06T10:30:00'),
    date_created: new Date('2025-06-12T13:10:00'),
    Models: null,
    project_name: 'Organica Foods',
    product_name: 'Organic Products'
  },
  {
    id: 6,
    title: 'TechMart Electronics',
    description: 'Consumer electronics pricing and positioning strategy',
    createdDate: '04/22/2025 14:15',
    updatedDate: '07/07/2025 11:20',
    version: '4',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 95,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '4',
    updatedAt: new Date('2025-07-07T11:20:00'),
    date_created: new Date('2025-04-22T14:15:00'),
    Models: null,
    project_name: 'TechMart Electronics',
    product_name: 'Electronics'
  },
  {
    id: 7,
    title: 'HealthPlus Pharmacy',
    description: 'Healthcare product optimization and compliance analysis',
    createdDate: '03/18/2025 10:45',
    updatedDate: '07/04/2025 16:30',
    version: '5',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 72,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '5',
    updatedAt: new Date('2025-07-04T16:30:00'),
    date_created: new Date('2025-03-18T10:45:00'),
    Models: null,
    project_name: 'HealthPlus Pharmacy',
    product_name: 'Healthcare Products'
  },
  {
    id: 8,
    title: 'Fashion Forward Retail',
    description: 'Seasonal pricing strategy for apparel and accessories',
    createdDate: '06/05/2025 09:30',
    updatedDate: '07/07/2025 14:45',
    version: '2',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 60,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '2',
    updatedAt: new Date('2025-07-07T14:45:00'),
    date_created: new Date('2025-06-05T09:30:00'),
    Models: null,
    project_name: 'Fashion Forward Retail',
    product_name: 'Apparel & Accessories'
  },
  {
    id: 9,
    title: 'AutoZone Parts & Services',
    description: 'Automotive parts pricing optimization and inventory management',
    createdDate: '05/20/2025 13:25',
    updatedDate: '07/06/2025 09:15',
    version: '3',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 83,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '3',
    updatedAt: new Date('2025-07-06T09:15:00'),
    date_created: new Date('2025-05-20T13:25:00'),
    Models: null,
    project_name: 'AutoZone Parts & Services',
    product_name: 'Automotive Parts'
  },
  {
    id: 10,
    title: 'BookWorld Publishing',
    description: 'Educational and entertainment book pricing analysis',
    createdDate: '04/08/2025 11:40',
    updatedDate: '07/03/2025 15:20',
    version: '6',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 91,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '6',
    updatedAt: new Date('2025-07-03T15:20:00'),
    date_created: new Date('2025-04-08T11:40:00'),
    Models: null,
    project_name: 'BookWorld Publishing',
    product_name: 'Books & Media'
  },
  {
    id: 11,
    title: 'SportsPro Equipment',
    description: 'Athletic gear and equipment competitive pricing strategy',
    createdDate: '06/28/2025 08:55',
    updatedDate: '07/07/2025 12:10',
    version: '1',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 45,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '1',
    updatedAt: new Date('2025-07-07T12:10:00'),
    date_created: new Date('2025-06-28T08:55:00'),
    Models: null,
    project_name: 'SportsPro Equipment',
    product_name: 'Sports Equipment'
  },
  {
    id: 12,
    title: 'HomeDecor Plus',
    description: 'Furniture and home accessories pricing optimization',
    createdDate: '05/15/2025 16:20',
    updatedDate: '07/05/2025 13:50',
    version: '3',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 76,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '3',
    updatedAt: new Date('2025-07-05T13:50:00'),
    date_created: new Date('2025-05-15T16:20:00'),
    Models: null,
    project_name: 'HomeDecor Plus',
    product_name: 'Home Decor'
  },
  {
    id: 13,
    title: 'PetCare Essentials',
    description: 'Pet food and accessories market analysis and pricing',
    createdDate: '06/10/2025 12:30',
    updatedDate: '07/06/2025 17:25',
    version: '2',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 69,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '2',
    updatedAt: new Date('2025-07-06T17:25:00'),
    date_created: new Date('2025-06-10T12:30:00'),
    Models: null,
    project_name: 'PetCare Essentials',
    product_name: 'Pet Products'
  },
  {
    id: 14,
    title: 'GourmetBites Restaurant',
    description: 'Restaurant menu pricing and food cost optimization',
    createdDate: '04/30/2025 14:10',
    updatedDate: '07/07/2025 10:35',
    version: '4',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 87,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '4',
    updatedAt: new Date('2025-07-07T10:35:00'),
    date_created: new Date('2025-04-30T14:10:00'),
    Models: null,
    project_name: 'GourmetBites Restaurant',
    product_name: 'Restaurant Menu'
  },
  {
    id: 15,
    title: 'TravelMax Adventures',
    description: 'Tourism and travel package pricing strategy and optimization',
    createdDate: '03/25/2025 09:15',
    updatedDate: '07/04/2025 14:40',
    version: '7',
    logo: '/logo.png',
    color: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
    progress: 94,
    features: ['Design Studio', 'Insights', 'Simulator', 'Output'],
    company_logo: '/logo.png',
    project_version: '7',
    updatedAt: new Date('2025-07-04T14:40:00'),
    date_created: new Date('2025-03-25T09:15:00'),
    Models: null,
    project_name: 'TravelMax Adventures',
    product_name: 'Travel Packages'
  }
];

// Default new project state
export const DEFAULT_NEW_PROJECT: NewProjectData = {
  projectName: '',
  company: '',
  targetBrand: '',
  projectType: '',
  version: '1.0',
  description: '',
  bannerColor: 'bg-gradient-to-br from-slate-900/90 via-slate-800/95 to-slate-900/90 backdrop-blur-lg',
  icon: 'FolderOpen',
  logo: '',
  retailers: [''],
  brands: [''],
  products: [''],
  status: 'Active',
  createdBy: 'John Doe' // This would come from auth context
};

// Default custom inputs state
export const DEFAULT_CUSTOM_INPUTS: CustomInputsState = {
  retailers: {},
  brands: {},
  products: {}
};

// Predefined options for dropdowns
export const PREDEFINED_RETAILERS = [
  'Walmart', 'Target', 'Amazon', 'Costco', 'Home Depot', 'Kroger', 'CVS Pharmacy', 
  'Walgreens', 'Best Buy', 'Lowes', 'Safeway', 'Publix', 'Meijer', 'Aldi'
];

export const PREDEFINED_BRANDS = [
  'Coca-Cola', 'Pepsi', 'Nestlé', 'Unilever', 'Procter & Gamble', 'Johnson & Johnson',
  'Nike', 'Adidas', 'Apple', 'Samsung', 'Sony', 'LG', 'General Mills', 'Kelloggs'
];

export const PREDEFINED_PRODUCTS = [
  'Soft Drinks', 'Snacks', 'Dairy Products', 'Frozen Foods', 'Personal Care',
  'Electronics', 'Clothing', 'Home & Garden', 'Health & Beauty', 'Automotive',
  'Sports & Outdoors', 'Books & Media', 'Toys & Games', 'Office Supplies'
];
